// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.dongbawen.proto;

/**
 * Protobuf type {@code com.dongbawen.proto.MyResponseList}
 */
public  final class MyResponseList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.dongbawen.proto.MyResponseList)
    MyResponseListOrBuilder {
  // Use MyResponseList.newBuilder() to construct.
  private MyResponseList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MyResponseList() {
    list_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MyResponseList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              list_ = new java.util.ArrayList<com.dongbawen.proto.MyResponse>();
              mutable_bitField0_ |= 0x00000001;
            }
            list_.add(
                input.readMessage(com.dongbawen.proto.MyResponse.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        list_ = java.util.Collections.unmodifiableList(list_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dongbawen.proto.StudentProto.internal_static_com_dongbawen_proto_MyResponseList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dongbawen.proto.StudentProto.internal_static_com_dongbawen_proto_MyResponseList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dongbawen.proto.MyResponseList.class, com.dongbawen.proto.MyResponseList.Builder.class);
  }

  public static final int LIST_FIELD_NUMBER = 1;
  private java.util.List<com.dongbawen.proto.MyResponse> list_;
  /**
   * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
   */
  public java.util.List<com.dongbawen.proto.MyResponse> getListList() {
    return list_;
  }
  /**
   * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
   */
  public java.util.List<? extends com.dongbawen.proto.MyResponseOrBuilder> 
      getListOrBuilderList() {
    return list_;
  }
  /**
   * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
   */
  public int getListCount() {
    return list_.size();
  }
  /**
   * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
   */
  public com.dongbawen.proto.MyResponse getList(int index) {
    return list_.get(index);
  }
  /**
   * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
   */
  public com.dongbawen.proto.MyResponseOrBuilder getListOrBuilder(
      int index) {
    return list_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < list_.size(); i++) {
      output.writeMessage(1, list_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < list_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, list_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dongbawen.proto.MyResponseList)) {
      return super.equals(obj);
    }
    com.dongbawen.proto.MyResponseList other = (com.dongbawen.proto.MyResponseList) obj;

    boolean result = true;
    result = result && getListList()
        .equals(other.getListList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getListCount() > 0) {
      hash = (37 * hash) + LIST_FIELD_NUMBER;
      hash = (53 * hash) + getListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dongbawen.proto.MyResponseList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dongbawen.proto.MyResponseList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dongbawen.proto.MyResponseList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dongbawen.proto.MyResponseList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dongbawen.proto.MyResponseList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dongbawen.proto.MyResponseList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dongbawen.proto.MyResponseList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dongbawen.proto.MyResponseList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dongbawen.proto.MyResponseList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dongbawen.proto.MyResponseList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dongbawen.proto.MyResponseList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.dongbawen.proto.MyResponseList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.dongbawen.proto.MyResponseList)
      com.dongbawen.proto.MyResponseListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dongbawen.proto.StudentProto.internal_static_com_dongbawen_proto_MyResponseList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dongbawen.proto.StudentProto.internal_static_com_dongbawen_proto_MyResponseList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dongbawen.proto.MyResponseList.class, com.dongbawen.proto.MyResponseList.Builder.class);
    }

    // Construct using com.dongbawen.proto.MyResponseList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getListFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (listBuilder_ == null) {
        list_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        listBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dongbawen.proto.StudentProto.internal_static_com_dongbawen_proto_MyResponseList_descriptor;
    }

    public com.dongbawen.proto.MyResponseList getDefaultInstanceForType() {
      return com.dongbawen.proto.MyResponseList.getDefaultInstance();
    }

    public com.dongbawen.proto.MyResponseList build() {
      com.dongbawen.proto.MyResponseList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dongbawen.proto.MyResponseList buildPartial() {
      com.dongbawen.proto.MyResponseList result = new com.dongbawen.proto.MyResponseList(this);
      int from_bitField0_ = bitField0_;
      if (listBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = java.util.Collections.unmodifiableList(list_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.list_ = list_;
      } else {
        result.list_ = listBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dongbawen.proto.MyResponseList) {
        return mergeFrom((com.dongbawen.proto.MyResponseList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dongbawen.proto.MyResponseList other) {
      if (other == com.dongbawen.proto.MyResponseList.getDefaultInstance()) return this;
      if (listBuilder_ == null) {
        if (!other.list_.isEmpty()) {
          if (list_.isEmpty()) {
            list_ = other.list_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureListIsMutable();
            list_.addAll(other.list_);
          }
          onChanged();
        }
      } else {
        if (!other.list_.isEmpty()) {
          if (listBuilder_.isEmpty()) {
            listBuilder_.dispose();
            listBuilder_ = null;
            list_ = other.list_;
            bitField0_ = (bitField0_ & ~0x00000001);
            listBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getListFieldBuilder() : null;
          } else {
            listBuilder_.addAllMessages(other.list_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dongbawen.proto.MyResponseList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dongbawen.proto.MyResponseList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.dongbawen.proto.MyResponse> list_ =
      java.util.Collections.emptyList();
    private void ensureListIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        list_ = new java.util.ArrayList<com.dongbawen.proto.MyResponse>(list_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dongbawen.proto.MyResponse, com.dongbawen.proto.MyResponse.Builder, com.dongbawen.proto.MyResponseOrBuilder> listBuilder_;

    /**
     * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
     */
    public java.util.List<com.dongbawen.proto.MyResponse> getListList() {
      if (listBuilder_ == null) {
        return java.util.Collections.unmodifiableList(list_);
      } else {
        return listBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
     */
    public int getListCount() {
      if (listBuilder_ == null) {
        return list_.size();
      } else {
        return listBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
     */
    public com.dongbawen.proto.MyResponse getList(int index) {
      if (listBuilder_ == null) {
        return list_.get(index);
      } else {
        return listBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
     */
    public Builder setList(
        int index, com.dongbawen.proto.MyResponse value) {
      if (listBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListIsMutable();
        list_.set(index, value);
        onChanged();
      } else {
        listBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
     */
    public Builder setList(
        int index, com.dongbawen.proto.MyResponse.Builder builderForValue) {
      if (listBuilder_ == null) {
        ensureListIsMutable();
        list_.set(index, builderForValue.build());
        onChanged();
      } else {
        listBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
     */
    public Builder addList(com.dongbawen.proto.MyResponse value) {
      if (listBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListIsMutable();
        list_.add(value);
        onChanged();
      } else {
        listBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
     */
    public Builder addList(
        int index, com.dongbawen.proto.MyResponse value) {
      if (listBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListIsMutable();
        list_.add(index, value);
        onChanged();
      } else {
        listBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
     */
    public Builder addList(
        com.dongbawen.proto.MyResponse.Builder builderForValue) {
      if (listBuilder_ == null) {
        ensureListIsMutable();
        list_.add(builderForValue.build());
        onChanged();
      } else {
        listBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
     */
    public Builder addList(
        int index, com.dongbawen.proto.MyResponse.Builder builderForValue) {
      if (listBuilder_ == null) {
        ensureListIsMutable();
        list_.add(index, builderForValue.build());
        onChanged();
      } else {
        listBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
     */
    public Builder addAllList(
        java.lang.Iterable<? extends com.dongbawen.proto.MyResponse> values) {
      if (listBuilder_ == null) {
        ensureListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, list_);
        onChanged();
      } else {
        listBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
     */
    public Builder clearList() {
      if (listBuilder_ == null) {
        list_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        listBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
     */
    public Builder removeList(int index) {
      if (listBuilder_ == null) {
        ensureListIsMutable();
        list_.remove(index);
        onChanged();
      } else {
        listBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
     */
    public com.dongbawen.proto.MyResponse.Builder getListBuilder(
        int index) {
      return getListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
     */
    public com.dongbawen.proto.MyResponseOrBuilder getListOrBuilder(
        int index) {
      if (listBuilder_ == null) {
        return list_.get(index);  } else {
        return listBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
     */
    public java.util.List<? extends com.dongbawen.proto.MyResponseOrBuilder> 
         getListOrBuilderList() {
      if (listBuilder_ != null) {
        return listBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(list_);
      }
    }
    /**
     * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
     */
    public com.dongbawen.proto.MyResponse.Builder addListBuilder() {
      return getListFieldBuilder().addBuilder(
          com.dongbawen.proto.MyResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
     */
    public com.dongbawen.proto.MyResponse.Builder addListBuilder(
        int index) {
      return getListFieldBuilder().addBuilder(
          index, com.dongbawen.proto.MyResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
     */
    public java.util.List<com.dongbawen.proto.MyResponse.Builder> 
         getListBuilderList() {
      return getListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dongbawen.proto.MyResponse, com.dongbawen.proto.MyResponse.Builder, com.dongbawen.proto.MyResponseOrBuilder> 
        getListFieldBuilder() {
      if (listBuilder_ == null) {
        listBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dongbawen.proto.MyResponse, com.dongbawen.proto.MyResponse.Builder, com.dongbawen.proto.MyResponseOrBuilder>(
                list_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        list_ = null;
      }
      return listBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.dongbawen.proto.MyResponseList)
  }

  // @@protoc_insertion_point(class_scope:com.dongbawen.proto.MyResponseList)
  private static final com.dongbawen.proto.MyResponseList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dongbawen.proto.MyResponseList();
  }

  public static com.dongbawen.proto.MyResponseList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MyResponseList>
      PARSER = new com.google.protobuf.AbstractParser<MyResponseList>() {
    public MyResponseList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyResponseList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MyResponseList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MyResponseList> getParserForType() {
    return PARSER;
  }

  public com.dongbawen.proto.MyResponseList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

