// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.dongbawen.proto;

public interface MyResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dongbawen.proto.MyResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
   */
  java.util.List<com.dongbawen.proto.MyResponse> 
      getListList();
  /**
   * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
   */
  com.dongbawen.proto.MyResponse getList(int index);
  /**
   * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
   */
  int getListCount();
  /**
   * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
   */
  java.util.List<? extends com.dongbawen.proto.MyResponseOrBuilder> 
      getListOrBuilderList();
  /**
   * <code>repeated .com.dongbawen.proto.MyResponse list = 1;</code>
   */
  com.dongbawen.proto.MyResponseOrBuilder getListOrBuilder(
      int index);
}
